#!/usr/bin/env node
/**
 * loredeck-plugin.mjs -- generated by scripts/sync-from-repo.mjs; do not edit.
 * Plugin entry point for the loredeck CLI. Defaults the workshop root to the
 * user's project so WIP canon projects land in their workspace, not the
 * plugin cache. Override with SAGA_WORKSHOP_ROOT.
 */
import path from 'node:path';
if (!process.env.SAGA_WORKSHOP_ROOT) {
  const base = process.env.CLAUDE_PROJECT_DIR || process.cwd();
  process.env.SAGA_WORKSHOP_ROOT = path.join(base, 'loredeck-workshop');
}
await import('./loredeck/loredeck-cli.mjs');
